modelname: "/home/master/catkin_ws/src/whole_body_ik/share/urdf/atlas.urdf"
base_link_frame: "pelvis"
lfoot_frame: "l_leg_akx"
rfoot_frame: "r_leg_akx"
lhand_frame: "l_arm_wry2"
rhand_frame: "r_arm_wry2"
head_frame: "neck_ry"
desired_joint_state_topic: "/atlas_raisim_ros/command_joint_states"
ndof: 29
jointNominalConfig: [0.03, 0,0.88 , 1 ,  0 , 0,0, 0, 0.035, 0, 0 , -1.57,  0  , 0,0,0,0,0,1.57 ,0,0,0,0 ,0, 0 , 0, -0.487608,  0.885098,   -0.4317, 0, 0 ,0 ,-0.487608, 0.885098,  -0.4317, 0]