modelname: "/home/master/catkin_ws/src/whole_body_ik/share/urdf/nao.urdf"
base_link_frame: "base_link"
lfoot_frame: "l_sole"
rfoot_frame: "r_sole"
lhand_frame: "LHand"
rhand_frame: "RHand"
head_frame: "Head"
desired_joint_state_topic: "/nao_raisim_ros/command_joint_states"
ndof: 26
jointNominalConfig: [0, 0, 0.32, 1, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, -0.3976, 0.85, -0.4427, -0.009, 0.0, 0.0, -0.3976, 0.85, -0.4427, -0.009, 1.5, 0.15, 0, -0.0349066, -1.5, 0, 1.5, -0.15, 0, 0.0349066, 1.5, 0]
